### PR TITLE
Add special type for the parsed token #248

### LINKED ISSUE #248: Make a special type for the parsed token
### The problem faced currently?
A lot of confusion is caused where a particular variable is an parsed token object or not.
### How can we solve it?
Make a new type called `TokenClaims` in the `utils` or `auth` package. This must the parameter and return type when ever the token claims are being passed around.
```golang
type TokenClaims map[string]interface{}
```
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

### PR DESCRIPTION
**Pull request by Inconnu08**
- Resolves #248
- Ran `GoImports`

### CODE REVIEW

**Comment by YourTechBud** [comment]
@Inconnu08 lets resolve the merge conflicts? I'll merge this request right in after that.

**Comment by Inconnu08** [comment]
@YourTechBud extremely sorry for the late response was afk.  Can you check if it's ok?

**Comment by YourTechBud** [comment]
@Inconnu08 Looks like you got back the old code which we had changed. Hard reset back to your last commit, soft reset by another commit, stash your changes, then merge v0.9.0. Then apply your stashed changes.

Or maybe you should start over again. The last request we merged changed a lot of things in the auth module!

**Comment by Inconnu08** [comment]
@YourTechBud woah! Might as well start over with the new changes. 😅

**Comment by YourTechBud** [comment]
Okay. Closing this request

**Pull request closed without merging**
