### PR TITLE
fixed issue of current data and timestamp #1043

### PR DESCRIPTION
**Pull request by khannaabhi**
1)the problem was the $1 or @p1 was replaced by current date or timestamp, but if $2 exists, the execution fails bcz respective doesn't exists in the query
2)so i decrease the number followed by $ or @p each by 1 in sanitiseUpdateQuery2
3)current_date doesn't work for sql server, so change it accordingly
4)fixed the test for update.go

### CODE REVIEW

**Comment by YourTechBud** [comment]
@khannaabhi did you test to see if currenttimestamp now works with all SQL databases?

**Comment by khannaabhi** [comment]
I tested it for postgres n SQL server...

**Comment by sharadregoti** [comment]
test for MySQL also

**Comment by YourTechBud** [comment]
Is this tested for MySQL @khannaabhi @sharadregoti ?

**Comment by sharadregoti** [comment]
nope

**Comment by sharadregoti** [comment]
@khannaabhi always pull the 18.1 before pushing your code

**Comment by YourTechBud** [comment]
@sharadregoti can someone confirm if this doesn't break MySQL

**Comment by khannaabhi** [comment]
> @khannaabhi always pull the 18.1 before pushing your code

I did. I think it changed after that. @YourTechBud , @sharadregoti I test it for MySQL as well, it's working

**Comment by YourTechBud** [comment]
Fixes #1043

**Pull request merged**
