### PR TITLE
Added Docs for Python Batch

### PR DESCRIPTION
**Pull request by AliabbasMerchant**
Just Batch was remaining. I added that.

Don't we have docs for aggregate?

2 more things:
1. docs/manual/database/transactions.md. Line 5, "coming soon" should be removed
2. docs/manual/getting-started/index.md. Lines 122-123, need to be updated

### CODE REVIEW

**Comment by YourTechBud** [comment]
@Jayesh333 come in on this one

**Comment by Jayesh333** [comment]
Transactions is not implemented yet. Only batch is implemented.
You can update line 122-123

We don't have docs for aggregate yet. That will require some time. We can make this docs live without aggregate

@AliabbasMerchant

**Comment by AliabbasMerchant** [comment]
Cool. Updated.

**Comment by YourTechBud** [comment]
@AliabbasMerchant whats the status on this one?

**Comment by Jayesh333** [comment]
It's fixed @YourTechBud

**Pull request merged**
