### PR TITLE
Initial Docker image for Space Cloud including Sample app with docker-compose file.

### PR DESCRIPTION
**Pull request by RawSanj**
Dockerized Space cloud and Sample app with docker-compose file to run the stack. 
Also added ability to deploy the stack with one-click to Play with docker.

### CODE REVIEW

**Comment by YourTechBud** [comment]
Thanks for this PR @RawSanj. I think its super helpful for people willing to try out space cloud for the first time. Tried to play with the docker link but didn't seem to work. Will try again tomorrow.

**Comment by RawSanj** [comment]
Yes, seems like there's some issues with Play with docker. It used to work really well before.
Hopefully they'll fix it soon. I'll check if they have modified the way it used to work or something is broken.

**Comment by YourTechBud** [comment]
Oh okay. So leave a comment if the link is functional again.

**Comment by YourTechBud** [comment]
@RawSanj any updates on this one?

**Comment by RawSanj** [comment]
I have created a new issue https://github.com/play-with-docker/play-with-docker/issues/341 for it.
One-Click deployment was very cool, hope they fix it soon.

**Comment by YourTechBud** [comment]
@RawSanj we are coming up with a hosted platform now. So having a play with docker template wont be required I guess. What are your thoughts?

**Comment by RawSanj** [comment]
Sure. That would be cool.

**Comment by YourTechBud** [comment]
Great. Will keep you posted. Closing this request for now

**Pull request closed without merging**
