### PR TITLE
fix error creating config via Init command on Windows

### PR DESCRIPTION
**Pull request by Inconnu08**
- resolves bug on config creation for windows
- typos
- clean up

### CODE REVIEW

**Comment by YourTechBud** [comment]
Looks perfect. Can you squash the commits into one? Also, keep the v0.7.0 branch as the base. You might have to create an new pull request for that!

**Comment by YourTechBud** [comment]
@Inconnu08 You seem to be on fire! Working more than us I guess!

**Comment by Inconnu08** [comment]
@YourTechBud haha I love the project, I'm learning a lot and enjoying it. Not sure about that. :P

**Comment by YourTechBud** [comment]
Haha! @Inconnu08 just squash these commits into one and pull a new PR keeping the base `v0.7.0`

**Pull request closed without merging**
