### PR TITLE
FileMan Auth is now an array

### LINKED ISSUE #298: Lets use an array instead of a map for the file man security rules
This is important since the alignment of a map can change during json parsing. We need to preserve the order of these rules.

### PR DESCRIPTION
**Pull request by AliabbasMerchant**
Fixes #298

### CODE REVIEW

**Comment by Jayesh333** [comment]
Will have to change the template and examples as well @AliabbasMerchant

**Comment by AliabbasMerchant** [comment]
@Jayesh333 Right. I forgot that. Have made the changes in the latest commit

**Comment by AliabbasMerchant** [comment]
@YourTechBud @Jayesh333 I have added docs for FileStore.  Please do not squash the commits while merging

**Comment by YourTechBud** [comment]
@AliabbasMerchant is the indentation for the rules array correct?

**Comment by AliabbasMerchant** [comment]
Yes. It is correct. And it is working properly. I checked

**Pull request merged**
