### PR TITLE
This pull request contains the entire GRPC support.

### PR DESCRIPTION
**Pull request by YourTechBud**

### CODE REVIEW

**Comment by YourTechBud** [comment]
@KhushalPShah need to bump the version number

**Comment by YourTechBud** [comment]
cannot merge this till #88 is resolved

**Comment by KhushalPShah** [comment]
> @KhushalPShah need to bump the version number

What Version number you talking about?

**Comment by KhushalPShah** [comment]
> > @KhushalPShah need to bump the version number
> 
> What Version number you talking about?

What should the version number be?
Is this going to be a minor change?

**Comment by KhushalPShah** [comment]
> cannot merge this till #88 is resolved

Have solved the issue.
Check it out.

**Comment by KhushalPShah** [comment]
> > cannot merge this till #88 is resolved
> 
> Have solved the issue.
> Check it out.

Also, since you had merged my previous Pull request yesterday, should I create a new Pull Request for this?

**Comment by YourTechBud** [comment]
@KhushalPShah create a new pull reqeuest. Bump the version to 0.6.0.

**Pull request merged**
