### PR TITLE
Add tests for Auth module

### PR DESCRIPTION
**Pull request by Inconnu08**
- Bumps `auth.go` test coverage to about 88.6%

### CODE REVIEW

**Comment by YourTechBud** [comment]
@Inconnu08 is it still a WIP? Edit the tile if its not.

**Comment by Inconnu08** [comment]
Yes whole package hence it was a WIP commit. But think it's better or separately pr for simplicity.

**Comment by YourTechBud** [comment]
@Inconnu08 lets keep it as a single pr but separate commits. I'll review one commit at a time. Will finally squash and merge.

**Comment by YourTechBud** [comment]
@Inconnu08 You think you can resolve the conflicts? I'll merge it right in after that

**Comment by Inconnu08** [comment]
@YourTechBud yes, I will resolve asap

**Comment by Inconnu08** [comment]
@YourTechBud resolved conflicts

**Pull request merged**
