### PR TITLE
WIP: Fix/57 need logging in space cloud

### LINKED ISSUE #57: Need logging in Space Cloud
Currently space cloud doesn't provide any logging. We need a proper logging mechanism with configurable levels.

### PR DESCRIPTION
**Pull request by ledex**
**This pull-request is still work in progress!** This pull-request fixes #57.

Things that are still todo:
- [x] Implement logging in web-UI → See [mission-control/issues/28](https://github.com/spaceuptech/mission-control/issues/28)
- [x] Documentation → See [space-docs/issues/12](https://github.com/spaceuptech/space-docs/issues/12)
- [ ] Change format of SysOut-logger
- [ ] A bit more testing
- [ ] Squash commits
- [ ] Add file-logger

### CODE REVIEW

**Comment by YourTechBud** [comment]
@ledex We can have separate issues for Documentation and the UI piece since they aren't really a part of this PR.

Do update this PR once the 2 and 3 points are done?

**Comment by YourTechBud** [comment]
Can we start with 2 types of logger? You've already implemented the `stdout` one. Can we also have a `file` implementation?

**Comment by YourTechBud** [comment]
Hey @ledex, do we have an ETA on this?

**Comment by ledex** [comment]
Yeah sorry for the big delay. I will be able to work on this topic this
weekend. So maybe this issue will be implemented by Sunday. But I can't
give a 100% guarantee.

Noorain Panjwani <notifications@github.com> schrieb am Mi., 18. Dez. 2019,
06:11:

**Comment by YourTechBud** [comment]
@ledex seems like logrus can be extended to achieve precisely what we want. I think we should use logrus as suggested by you in our initial conversations

**Comment by ledex** [comment]
Okay, @YourTechBud. Sorry that I did not have any time to implement this in its full glory. I'll get back to you when my schedule is a bit freer.

**Pull request closed without merging**
