### PR TITLE
Enhancement: Connection parser – automatically parses connection string from info, can read passwords from either env or file

### PR DESCRIPTION
**Pull request by ollykel**
# Enhancement: Connection Parser
Hey there!

I had some time to contribute an enhancement this week. It's related to issue #150, which I raised last week about reading passwords from secure files. I went a step further and implemented an extension of the config package that automatically parses connection strings for each database using its components - user, password, hostname, etc. While doing this, it gives the option to read passwords from either an environment variable or a file by prefixing the password with either "ENV:" or "FILE:". The connection data is stored in a struct called ConnConfig (see config/conn.go), which is included in each CrudStub under the field name "Connection".

Below is the implementation of ConnConfig:
```go
// largely based on go-sql-driver's ConnConfig struct
// 	see: https://godoc.org/go-sql-driver/mysql#ConnConfig
// also based on lib/pq's connection string parameters
// 	see: https://godoc.org/github.com/lib/pq
type ConnConfig struct {
	User		string	`json:"user" yaml:"user"`
	// Auth provides source of password, either env or file
	Auth		string	`json:"auth" yaml:"auth"`
	DBName		string	`json:"dbName" yaml:"dbName"`
	// Protocol ex: "tcp"
	Protocol	string	`json:"protocol" yaml:"protocol"`
	Host		string	`json:"host" yaml:"host"`
	Port		string	`json:"port" yaml:"port"`
	SSLMode		sslMode	`json:"sslMode" yaml:"sslMode"`
	SSLCert		string	`json:"sslCert,omitempty" yaml:"sslCert,omitempty"`
	SSLKey		string	`json:"sslKey,omitempty" yaml:"sslKey,omitempty"`
	SSLRootCert	string	`json:"sslRootCert,omitempty" yaml:"sslRootCert,omitempty"`
	Params		map[string]string `json:"params,omitempty" yaml:"params,omitempty"`
}//-- end SQLConnConfig struct
```
Note: sslMode is based on lib/pq's sslMode param, which has four possible values: "require" , "disable", "verify-ca", and "verify-full". In databases with only true or false options for ssl, disable equals false and all other settings equal true.

The file config/parseconn.go contains functions to parse connection strings for all three of the supported databases from a ConnConfig struct.

The file config/generate.go has been modified to generate a ConnConfig struct from a survey and save it to the input struct during space-cloud init. This makes use of the method ConnConfig.FromSurvey(), which is located in the file config/conn.go.

To ensure backward compatibility, the original "Conn" field is still present in each CrudStub; if it is non-empty, space-cloud run defaults to using it instead of parsing a connection string.

## Specifying how to get a password
The ConnConfig struct, as shown above, contains a field 'Auth", which is where a user can specify how to get a password. There are three possible options for this: a plain string, a file, or an environment variable. These are specified by the prefixes "STRING", "FILE", and "ENV". Below is an example of each:
```yaml
connection:
...
    auth: STRING:my_password
    auth: FILE:/run/secrets/my_password.txt
    auth: ENV:MY_PASSWORD 
...
```

## Additional Changes:
The following changes were made to support this enhancement:
- Each of the structs in config/config.go has been modified to make use of "omitempty" field tag where appropriate. This prevents the yaml parser from writing the fields to a file if they are empty.
- The func writeConfig in config/generate.go has been rewritten to use a yaml encoder instead of an html template to write to the config file. Because of the previous change, the func does not write empty fields to the file, producing output identical to the output from the template.
- The template in config/template.go has been rewritten as a plain yaml string instead of a template. The func writeConfig uses yaml.Decoder.Decode() to generate a default Project struct from this template before adding the user input and writing to a file.

### CODE REVIEW

**Comment by YourTechBud** [comment]
Hey buddy. Thats a lot of work i see here! Thanks a ton. I'll review this tomorrow or day after. To start with, can you squash all commits into one?

**Comment by YourTechBud** [comment]
Hey @ollykel. I'm sorry i haven't been able to go through your code yet. Will clear this in a couple of weeks.

**Comment by ollykel** [comment]
It's ok, it's a big commit haha. I've been busy this week too, I'll finish squashing the commits today.

Should I reopen the pull request on v0.8.0, btw? I didn't see that last time.

**Comment by YourTechBud** [comment]
@ollykel yes. Change the base to v0.8.0.

**Comment by YourTechBud** [comment]
Its too big a request. We should break this into smaller chunks. Closing it for now

**Pull request closed without merging**
