### PR TITLE
No scrollbar visible in the docs pages [Patch]

### PR DESCRIPTION
**Pull request by nicknonis**
created initial request here: https://github.com/YourTechBud/space-cloud/pull/1
 
[docs/public/docs/sass/index/_content.scss]
changes made to .main-wrapper {.content-wrapper{ 
-left property change to 0
-padding property changed to 40px 0px 0px 360px;

[docs/public/docs/sass/index/_sidebar.scss]
added a z-index of 1 to .main-wrapper >  .desktop-docs-sidebar

### CODE REVIEW

**Comment by YourTechBud** [comment]
This fixes #135. Can you squash all the commits into one? @akshayjj1997 quickly have a look at this and approve if everything looks good!

**Comment by YourTechBud** [comment]
> Problem exists in Mozilla Firefox, Google Chrome
OS: Windows 10

See if this is fixed in these environments as well!

**Comment by akshayjj1997** [comment]
The content feels like stacked to the left. Needs to change the class="col s12 l6" of "content-wrapper" inside index.handlebars to s12 l7 or s12 l8

**Comment by YourTechBud** [comment]
Yeah the width of the content seems to be a bit too packed now. @akshayjj1997 do we even need a grid there? Why not have a grid inside the div to which the padding is applied?

**Comment by nicknonis** [comment]
I think I've squashed the commits, sorry first time pull request :) 
Adding a grid to the div sounds like an improvement.

**Comment by akshayjj1997** [comment]
@YourTechBud Yes we need a grid there, otherwise the entire content will take the full width. And the gird is placed inside the div to which the padding is applied

**Comment by YourTechBud** [comment]
No problem @nicknonis! Glad to be your first contribution! Can you make the necessary changes suggested by @akshayjj1997?

**Comment by nicknonis** [comment]
okay done! is it any better now?

**Pull request merged**
